
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  password: "##ali##!@#$%"

development:
  <<: *default
  database: ask_development

test:
  <<: *default
  database: ask_test
 
production:
  <<: *default
  database: ask_production
  username: ask
  password: <%= ENV['ASK_DATABASE_PASSWORD'] %>
